services:
    # Main Laravel Application
    app:
        build: .
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # Nginx Web Server
    web:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app-network

    # MySQL Database
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: "${MYSQL_EXTRA_OPTIONS:-}"
        ports:
            - "3306:3306"
        networks:
            - app-network

    # Queue Worker
    worker:
        build: .
        command: php artisan queue:work --tries=3
        restart: unless-stopped
        depends_on:
            - app
            - mysql
        networks:
            - app-network

    # Reverb WebSocket Server
    reverb:
        build: .
        command: "php artisan reverb:start --debug"

        container_name: reverb
        ports:
            - "${REVERB_PORT:-8080}:8080"
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
